// Code generated by go-swagger; DO NOT EDIT.

package tapi_common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// GetDataContextTopologyUUIDLinkLinkUUIDURL generates an URL for the get data context topology UUID link link UUID operation
type GetDataContextTopologyUUIDLinkLinkUUIDURL struct {
	LinkUUID string
	UUID     string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetDataContextTopologyUUIDLinkLinkUUIDURL) WithBasePath(bp string) *GetDataContextTopologyUUIDLinkLinkUUIDURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetDataContextTopologyUUIDLinkLinkUUIDURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetDataContextTopologyUUIDLinkLinkUUIDURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/data/context/topology={uuid}/link={link-uuid}/"

	linkUUID := o.LinkUUID
	if linkUUID != "" {
		_path = strings.Replace(_path, "{link-uuid}", linkUUID, -1)
	} else {
		return nil, errors.New("LinkUUID is required on GetDataContextTopologyUUIDLinkLinkUUIDURL")
	}

	uuid := o.UUID
	if uuid != "" {
		_path = strings.Replace(_path, "{uuid}", uuid, -1)
	} else {
		return nil, errors.New("UUID is required on GetDataContextTopologyUUIDLinkLinkUUIDURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetDataContextTopologyUUIDLinkLinkUUIDURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetDataContextTopologyUUIDLinkLinkUUIDURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetDataContextTopologyUUIDLinkLinkUUIDURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetDataContextTopologyUUIDLinkLinkUUIDURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetDataContextTopologyUUIDLinkLinkUUIDURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetDataContextTopologyUUIDLinkLinkUUIDURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
