// Code generated by go-swagger; DO NOT EDIT.

package tapi_common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDataContextServiceInterfacePointUUIDHandlerFunc turns a function with the right signature into a get data context service interface point UUID handler
type GetDataContextServiceInterfacePointUUIDHandlerFunc func(GetDataContextServiceInterfacePointUUIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDataContextServiceInterfacePointUUIDHandlerFunc) Handle(params GetDataContextServiceInterfacePointUUIDParams) middleware.Responder {
	return fn(params)
}

// GetDataContextServiceInterfacePointUUIDHandler interface for that can handle valid get data context service interface point UUID params
type GetDataContextServiceInterfacePointUUIDHandler interface {
	Handle(GetDataContextServiceInterfacePointUUIDParams) middleware.Responder
}

// NewGetDataContextServiceInterfacePointUUID creates a new http.Handler for the get data context service interface point UUID operation
func NewGetDataContextServiceInterfacePointUUID(ctx *middleware.Context, handler GetDataContextServiceInterfacePointUUIDHandler) *GetDataContextServiceInterfacePointUUID {
	return &GetDataContextServiceInterfacePointUUID{Context: ctx, Handler: handler}
}

/*GetDataContextServiceInterfacePointUUID swagger:route GET /data/context/service-interface-point={uuid}/ tapi-common getDataContextServiceInterfacePointUuid

returns tapi.common.context.ServiceInterfacePoint

*/
type GetDataContextServiceInterfacePointUUID struct {
	Context *middleware.Context
	Handler GetDataContextServiceInterfacePointUUIDHandler
}

func (o *GetDataContextServiceInterfacePointUUID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDataContextServiceInterfacePointUUIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
