// Code generated by go-swagger; DO NOT EDIT.

package tapi_common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDataContextHandlerFunc turns a function with the right signature into a get data context handler
type GetDataContextHandlerFunc func(GetDataContextParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDataContextHandlerFunc) Handle(params GetDataContextParams) middleware.Responder {
	return fn(params)
}

// GetDataContextHandler interface for that can handle valid get data context params
type GetDataContextHandler interface {
	Handle(GetDataContextParams) middleware.Responder
}

// NewGetDataContext creates a new http.Handler for the get data context operation
func NewGetDataContext(ctx *middleware.Context, handler GetDataContextHandler) *GetDataContext {
	return &GetDataContext{Context: ctx, Handler: handler}
}

/*GetDataContext swagger:route GET /data/context/ tapi-common getDataContext

returns tapi.common.Context

*/
type GetDataContext struct {
	Context *middleware.Context
	Handler GetDataContextHandler
}

func (o *GetDataContext) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDataContextParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
