// Code generated by go-swagger; DO NOT EDIT.

package tapi_common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/presto/models"
)

// GetDataContextConnectivityServiceUUIDOKCode is the HTTP code returned for type GetDataContextConnectivityServiceUUIDOK
const GetDataContextConnectivityServiceUUIDOKCode int = 200

/*GetDataContextConnectivityServiceUUIDOK tapi.connectivity.connectivitycontext.ConnectivityService

swagger:response getDataContextConnectivityServiceUuidOK
*/
type GetDataContextConnectivityServiceUUIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiConnectivityConnectivitycontextConnectivityService `json:"body,omitempty"`
}

// NewGetDataContextConnectivityServiceUUIDOK creates GetDataContextConnectivityServiceUUIDOK with default headers values
func NewGetDataContextConnectivityServiceUUIDOK() *GetDataContextConnectivityServiceUUIDOK {

	return &GetDataContextConnectivityServiceUUIDOK{}
}

// WithPayload adds the payload to the get data context connectivity service Uuid o k response
func (o *GetDataContextConnectivityServiceUUIDOK) WithPayload(payload *models.TapiConnectivityConnectivitycontextConnectivityService) *GetDataContextConnectivityServiceUUIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data context connectivity service Uuid o k response
func (o *GetDataContextConnectivityServiceUUIDOK) SetPayload(payload *models.TapiConnectivityConnectivitycontextConnectivityService) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataContextConnectivityServiceUUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDataContextConnectivityServiceUUIDBadRequestCode is the HTTP code returned for type GetDataContextConnectivityServiceUUIDBadRequest
const GetDataContextConnectivityServiceUUIDBadRequestCode int = 400

/*GetDataContextConnectivityServiceUUIDBadRequest Internal error

swagger:response getDataContextConnectivityServiceUuidBadRequest
*/
type GetDataContextConnectivityServiceUUIDBadRequest struct {
}

// NewGetDataContextConnectivityServiceUUIDBadRequest creates GetDataContextConnectivityServiceUUIDBadRequest with default headers values
func NewGetDataContextConnectivityServiceUUIDBadRequest() *GetDataContextConnectivityServiceUUIDBadRequest {

	return &GetDataContextConnectivityServiceUUIDBadRequest{}
}

// WriteResponse to the client
func (o *GetDataContextConnectivityServiceUUIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
