// Code generated by go-swagger; DO NOT EDIT.

package tapi_common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/presto/models"
)

// GetDataContextConnectionUUIDOKCode is the HTTP code returned for type GetDataContextConnectionUUIDOK
const GetDataContextConnectionUUIDOKCode int = 200

/*GetDataContextConnectionUUIDOK tapi.connectivity.Connection

swagger:response getDataContextConnectionUuidOK
*/
type GetDataContextConnectionUUIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiConnectivityConnection `json:"body,omitempty"`
}

// NewGetDataContextConnectionUUIDOK creates GetDataContextConnectionUUIDOK with default headers values
func NewGetDataContextConnectionUUIDOK() *GetDataContextConnectionUUIDOK {

	return &GetDataContextConnectionUUIDOK{}
}

// WithPayload adds the payload to the get data context connection Uuid o k response
func (o *GetDataContextConnectionUUIDOK) WithPayload(payload *models.TapiConnectivityConnection) *GetDataContextConnectionUUIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data context connection Uuid o k response
func (o *GetDataContextConnectionUUIDOK) SetPayload(payload *models.TapiConnectivityConnection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataContextConnectionUUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDataContextConnectionUUIDBadRequestCode is the HTTP code returned for type GetDataContextConnectionUUIDBadRequest
const GetDataContextConnectionUUIDBadRequestCode int = 400

/*GetDataContextConnectionUUIDBadRequest Internal error

swagger:response getDataContextConnectionUuidBadRequest
*/
type GetDataContextConnectionUUIDBadRequest struct {
}

// NewGetDataContextConnectionUUIDBadRequest creates GetDataContextConnectionUUIDBadRequest with default headers values
func NewGetDataContextConnectionUUIDBadRequest() *GetDataContextConnectionUUIDBadRequest {

	return &GetDataContextConnectionUUIDBadRequest{}
}

// WriteResponse to the client
func (o *GetDataContextConnectionUUIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
