// Code generated by go-swagger; DO NOT EDIT.

package tapi_common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDataContextConnectionUUIDHandlerFunc turns a function with the right signature into a get data context connection UUID handler
type GetDataContextConnectionUUIDHandlerFunc func(GetDataContextConnectionUUIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDataContextConnectionUUIDHandlerFunc) Handle(params GetDataContextConnectionUUIDParams) middleware.Responder {
	return fn(params)
}

// GetDataContextConnectionUUIDHandler interface for that can handle valid get data context connection UUID params
type GetDataContextConnectionUUIDHandler interface {
	Handle(GetDataContextConnectionUUIDParams) middleware.Responder
}

// NewGetDataContextConnectionUUID creates a new http.Handler for the get data context connection UUID operation
func NewGetDataContextConnectionUUID(ctx *middleware.Context, handler GetDataContextConnectionUUIDHandler) *GetDataContextConnectionUUID {
	return &GetDataContextConnectionUUID{Context: ctx, Handler: handler}
}

/*GetDataContextConnectionUUID swagger:route GET /data/context/connection={uuid}/ tapi-common getDataContextConnectionUuid

returns tapi.connectivity.Connection

*/
type GetDataContextConnectionUUID struct {
	Context *middleware.Context
	Handler GetDataContextConnectionUUIDHandler
}

func (o *GetDataContextConnectionUUID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDataContextConnectionUUIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
