// Code generated by go-swagger; DO NOT EDIT.

package tapi_common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/presto/models"
)

// GetDataContextPathCompServiceUUIDOKCode is the HTTP code returned for type GetDataContextPathCompServiceUUIDOK
const GetDataContextPathCompServiceUUIDOKCode int = 200

/*GetDataContextPathCompServiceUUIDOK tapi.path.computation.PathComputationService

swagger:response getDataContextPathCompServiceUuidOK
*/
type GetDataContextPathCompServiceUUIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiPathComputationPathComputationService `json:"body,omitempty"`
}

// NewGetDataContextPathCompServiceUUIDOK creates GetDataContextPathCompServiceUUIDOK with default headers values
func NewGetDataContextPathCompServiceUUIDOK() *GetDataContextPathCompServiceUUIDOK {

	return &GetDataContextPathCompServiceUUIDOK{}
}

// WithPayload adds the payload to the get data context path comp service Uuid o k response
func (o *GetDataContextPathCompServiceUUIDOK) WithPayload(payload *models.TapiPathComputationPathComputationService) *GetDataContextPathCompServiceUUIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data context path comp service Uuid o k response
func (o *GetDataContextPathCompServiceUUIDOK) SetPayload(payload *models.TapiPathComputationPathComputationService) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataContextPathCompServiceUUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDataContextPathCompServiceUUIDBadRequestCode is the HTTP code returned for type GetDataContextPathCompServiceUUIDBadRequest
const GetDataContextPathCompServiceUUIDBadRequestCode int = 400

/*GetDataContextPathCompServiceUUIDBadRequest Internal error

swagger:response getDataContextPathCompServiceUuidBadRequest
*/
type GetDataContextPathCompServiceUUIDBadRequest struct {
}

// NewGetDataContextPathCompServiceUUIDBadRequest creates GetDataContextPathCompServiceUUIDBadRequest with default headers values
func NewGetDataContextPathCompServiceUUIDBadRequest() *GetDataContextPathCompServiceUUIDBadRequest {

	return &GetDataContextPathCompServiceUUIDBadRequest{}
}

// WriteResponse to the client
func (o *GetDataContextPathCompServiceUUIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
