// Code generated by go-swagger; DO NOT EDIT.

package tapi_common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/presto/models"
)

// GetDataContextServiceInterfacePointUUIDOKCode is the HTTP code returned for type GetDataContextServiceInterfacePointUUIDOK
const GetDataContextServiceInterfacePointUUIDOKCode int = 200

/*GetDataContextServiceInterfacePointUUIDOK tapi.common.context.ServiceInterfacePoint

swagger:response getDataContextServiceInterfacePointUuidOK
*/
type GetDataContextServiceInterfacePointUUIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiCommonContextServiceInterfacePoint `json:"body,omitempty"`
}

// NewGetDataContextServiceInterfacePointUUIDOK creates GetDataContextServiceInterfacePointUUIDOK with default headers values
func NewGetDataContextServiceInterfacePointUUIDOK() *GetDataContextServiceInterfacePointUUIDOK {

	return &GetDataContextServiceInterfacePointUUIDOK{}
}

// WithPayload adds the payload to the get data context service interface point Uuid o k response
func (o *GetDataContextServiceInterfacePointUUIDOK) WithPayload(payload *models.TapiCommonContextServiceInterfacePoint) *GetDataContextServiceInterfacePointUUIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data context service interface point Uuid o k response
func (o *GetDataContextServiceInterfacePointUUIDOK) SetPayload(payload *models.TapiCommonContextServiceInterfacePoint) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataContextServiceInterfacePointUUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDataContextServiceInterfacePointUUIDBadRequestCode is the HTTP code returned for type GetDataContextServiceInterfacePointUUIDBadRequest
const GetDataContextServiceInterfacePointUUIDBadRequestCode int = 400

/*GetDataContextServiceInterfacePointUUIDBadRequest Internal error

swagger:response getDataContextServiceInterfacePointUuidBadRequest
*/
type GetDataContextServiceInterfacePointUUIDBadRequest struct {
}

// NewGetDataContextServiceInterfacePointUUIDBadRequest creates GetDataContextServiceInterfacePointUUIDBadRequest with default headers values
func NewGetDataContextServiceInterfacePointUUIDBadRequest() *GetDataContextServiceInterfacePointUUIDBadRequest {

	return &GetDataContextServiceInterfacePointUUIDBadRequest{}
}

// WriteResponse to the client
func (o *GetDataContextServiceInterfacePointUUIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
