// Code generated by go-swagger; DO NOT EDIT.

package tapi_path_computation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/damianoneill/presto/models"
)

// NewPostOperationsComputeP2PPathParams creates a new PostOperationsComputeP2PPathParams object
// no default values defined in spec.
func NewPostOperationsComputeP2PPathParams() PostOperationsComputeP2PPathParams {

	return PostOperationsComputeP2PPathParams{}
}

// PostOperationsComputeP2PPathParams contains all the bound params for the post operations compute p2 p path operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostOperationsComputeP2PPath
type PostOperationsComputeP2PPathParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	BodyParam *models.TapiPathComputationComputeP2PPathInput
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostOperationsComputeP2PPathParams() beforehand.
func (o *PostOperationsComputeP2PPathParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.TapiPathComputationComputeP2PPathInput
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("bodyParam", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.BodyParam = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
