// Code generated by go-swagger; DO NOT EDIT.

package tapi_connectivity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/presto/models"
)

// PostOperationsGetConnectivityServiceDetailsOKCode is the HTTP code returned for type PostOperationsGetConnectivityServiceDetailsOK
const PostOperationsGetConnectivityServiceDetailsOKCode int = 200

/*PostOperationsGetConnectivityServiceDetailsOK Correct response

swagger:response postOperationsGetConnectivityServiceDetailsOK
*/
type PostOperationsGetConnectivityServiceDetailsOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiConnectivityGetConnectivityServiceDetailsOutput `json:"body,omitempty"`
}

// NewPostOperationsGetConnectivityServiceDetailsOK creates PostOperationsGetConnectivityServiceDetailsOK with default headers values
func NewPostOperationsGetConnectivityServiceDetailsOK() *PostOperationsGetConnectivityServiceDetailsOK {

	return &PostOperationsGetConnectivityServiceDetailsOK{}
}

// WithPayload adds the payload to the post operations get connectivity service details o k response
func (o *PostOperationsGetConnectivityServiceDetailsOK) WithPayload(payload *models.TapiConnectivityGetConnectivityServiceDetailsOutput) *PostOperationsGetConnectivityServiceDetailsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations get connectivity service details o k response
func (o *PostOperationsGetConnectivityServiceDetailsOK) SetPayload(payload *models.TapiConnectivityGetConnectivityServiceDetailsOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsGetConnectivityServiceDetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsGetConnectivityServiceDetailsCreatedCode is the HTTP code returned for type PostOperationsGetConnectivityServiceDetailsCreated
const PostOperationsGetConnectivityServiceDetailsCreatedCode int = 201

/*PostOperationsGetConnectivityServiceDetailsCreated No response

swagger:response postOperationsGetConnectivityServiceDetailsCreated
*/
type PostOperationsGetConnectivityServiceDetailsCreated struct {
}

// NewPostOperationsGetConnectivityServiceDetailsCreated creates PostOperationsGetConnectivityServiceDetailsCreated with default headers values
func NewPostOperationsGetConnectivityServiceDetailsCreated() *PostOperationsGetConnectivityServiceDetailsCreated {

	return &PostOperationsGetConnectivityServiceDetailsCreated{}
}

// WriteResponse to the client
func (o *PostOperationsGetConnectivityServiceDetailsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsGetConnectivityServiceDetailsBadRequestCode is the HTTP code returned for type PostOperationsGetConnectivityServiceDetailsBadRequest
const PostOperationsGetConnectivityServiceDetailsBadRequestCode int = 400

/*PostOperationsGetConnectivityServiceDetailsBadRequest Internal error

swagger:response postOperationsGetConnectivityServiceDetailsBadRequest
*/
type PostOperationsGetConnectivityServiceDetailsBadRequest struct {
}

// NewPostOperationsGetConnectivityServiceDetailsBadRequest creates PostOperationsGetConnectivityServiceDetailsBadRequest with default headers values
func NewPostOperationsGetConnectivityServiceDetailsBadRequest() *PostOperationsGetConnectivityServiceDetailsBadRequest {

	return &PostOperationsGetConnectivityServiceDetailsBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsGetConnectivityServiceDetailsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
