// Code generated by go-swagger; DO NOT EDIT.

package tapi_connectivity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/presto/models"
)

// PostOperationsUpdateConnectivityServiceOKCode is the HTTP code returned for type PostOperationsUpdateConnectivityServiceOK
const PostOperationsUpdateConnectivityServiceOKCode int = 200

/*PostOperationsUpdateConnectivityServiceOK Correct response

swagger:response postOperationsUpdateConnectivityServiceOK
*/
type PostOperationsUpdateConnectivityServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiConnectivityUpdateConnectivityServiceOutput `json:"body,omitempty"`
}

// NewPostOperationsUpdateConnectivityServiceOK creates PostOperationsUpdateConnectivityServiceOK with default headers values
func NewPostOperationsUpdateConnectivityServiceOK() *PostOperationsUpdateConnectivityServiceOK {

	return &PostOperationsUpdateConnectivityServiceOK{}
}

// WithPayload adds the payload to the post operations update connectivity service o k response
func (o *PostOperationsUpdateConnectivityServiceOK) WithPayload(payload *models.TapiConnectivityUpdateConnectivityServiceOutput) *PostOperationsUpdateConnectivityServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations update connectivity service o k response
func (o *PostOperationsUpdateConnectivityServiceOK) SetPayload(payload *models.TapiConnectivityUpdateConnectivityServiceOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsUpdateConnectivityServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsUpdateConnectivityServiceCreatedCode is the HTTP code returned for type PostOperationsUpdateConnectivityServiceCreated
const PostOperationsUpdateConnectivityServiceCreatedCode int = 201

/*PostOperationsUpdateConnectivityServiceCreated No response

swagger:response postOperationsUpdateConnectivityServiceCreated
*/
type PostOperationsUpdateConnectivityServiceCreated struct {
}

// NewPostOperationsUpdateConnectivityServiceCreated creates PostOperationsUpdateConnectivityServiceCreated with default headers values
func NewPostOperationsUpdateConnectivityServiceCreated() *PostOperationsUpdateConnectivityServiceCreated {

	return &PostOperationsUpdateConnectivityServiceCreated{}
}

// WriteResponse to the client
func (o *PostOperationsUpdateConnectivityServiceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsUpdateConnectivityServiceBadRequestCode is the HTTP code returned for type PostOperationsUpdateConnectivityServiceBadRequest
const PostOperationsUpdateConnectivityServiceBadRequestCode int = 400

/*PostOperationsUpdateConnectivityServiceBadRequest Internal error

swagger:response postOperationsUpdateConnectivityServiceBadRequest
*/
type PostOperationsUpdateConnectivityServiceBadRequest struct {
}

// NewPostOperationsUpdateConnectivityServiceBadRequest creates PostOperationsUpdateConnectivityServiceBadRequest with default headers values
func NewPostOperationsUpdateConnectivityServiceBadRequest() *PostOperationsUpdateConnectivityServiceBadRequest {

	return &PostOperationsUpdateConnectivityServiceBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsUpdateConnectivityServiceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
