// Code generated by go-swagger; DO NOT EDIT.

package tapi_connectivity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/presto/models"
)

// PostOperationsDeleteConnectivityServiceOKCode is the HTTP code returned for type PostOperationsDeleteConnectivityServiceOK
const PostOperationsDeleteConnectivityServiceOKCode int = 200

/*PostOperationsDeleteConnectivityServiceOK Correct response

swagger:response postOperationsDeleteConnectivityServiceOK
*/
type PostOperationsDeleteConnectivityServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiConnectivityDeleteConnectivityServiceOutput `json:"body,omitempty"`
}

// NewPostOperationsDeleteConnectivityServiceOK creates PostOperationsDeleteConnectivityServiceOK with default headers values
func NewPostOperationsDeleteConnectivityServiceOK() *PostOperationsDeleteConnectivityServiceOK {

	return &PostOperationsDeleteConnectivityServiceOK{}
}

// WithPayload adds the payload to the post operations delete connectivity service o k response
func (o *PostOperationsDeleteConnectivityServiceOK) WithPayload(payload *models.TapiConnectivityDeleteConnectivityServiceOutput) *PostOperationsDeleteConnectivityServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations delete connectivity service o k response
func (o *PostOperationsDeleteConnectivityServiceOK) SetPayload(payload *models.TapiConnectivityDeleteConnectivityServiceOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsDeleteConnectivityServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsDeleteConnectivityServiceCreatedCode is the HTTP code returned for type PostOperationsDeleteConnectivityServiceCreated
const PostOperationsDeleteConnectivityServiceCreatedCode int = 201

/*PostOperationsDeleteConnectivityServiceCreated No response

swagger:response postOperationsDeleteConnectivityServiceCreated
*/
type PostOperationsDeleteConnectivityServiceCreated struct {
}

// NewPostOperationsDeleteConnectivityServiceCreated creates PostOperationsDeleteConnectivityServiceCreated with default headers values
func NewPostOperationsDeleteConnectivityServiceCreated() *PostOperationsDeleteConnectivityServiceCreated {

	return &PostOperationsDeleteConnectivityServiceCreated{}
}

// WriteResponse to the client
func (o *PostOperationsDeleteConnectivityServiceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsDeleteConnectivityServiceBadRequestCode is the HTTP code returned for type PostOperationsDeleteConnectivityServiceBadRequest
const PostOperationsDeleteConnectivityServiceBadRequestCode int = 400

/*PostOperationsDeleteConnectivityServiceBadRequest Internal error

swagger:response postOperationsDeleteConnectivityServiceBadRequest
*/
type PostOperationsDeleteConnectivityServiceBadRequest struct {
}

// NewPostOperationsDeleteConnectivityServiceBadRequest creates PostOperationsDeleteConnectivityServiceBadRequest with default headers values
func NewPostOperationsDeleteConnectivityServiceBadRequest() *PostOperationsDeleteConnectivityServiceBadRequest {

	return &PostOperationsDeleteConnectivityServiceBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsDeleteConnectivityServiceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
