// Code generated by go-swagger; DO NOT EDIT.

package tapi_connectivity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/presto/models"
)

// PostOperationsGetConnectivityServiceListOKCode is the HTTP code returned for type PostOperationsGetConnectivityServiceListOK
const PostOperationsGetConnectivityServiceListOKCode int = 200

/*PostOperationsGetConnectivityServiceListOK Correct response

swagger:response postOperationsGetConnectivityServiceListOK
*/
type PostOperationsGetConnectivityServiceListOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiConnectivityGetConnectivityServiceListOutput `json:"body,omitempty"`
}

// NewPostOperationsGetConnectivityServiceListOK creates PostOperationsGetConnectivityServiceListOK with default headers values
func NewPostOperationsGetConnectivityServiceListOK() *PostOperationsGetConnectivityServiceListOK {

	return &PostOperationsGetConnectivityServiceListOK{}
}

// WithPayload adds the payload to the post operations get connectivity service list o k response
func (o *PostOperationsGetConnectivityServiceListOK) WithPayload(payload *models.TapiConnectivityGetConnectivityServiceListOutput) *PostOperationsGetConnectivityServiceListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations get connectivity service list o k response
func (o *PostOperationsGetConnectivityServiceListOK) SetPayload(payload *models.TapiConnectivityGetConnectivityServiceListOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsGetConnectivityServiceListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsGetConnectivityServiceListCreatedCode is the HTTP code returned for type PostOperationsGetConnectivityServiceListCreated
const PostOperationsGetConnectivityServiceListCreatedCode int = 201

/*PostOperationsGetConnectivityServiceListCreated No response

swagger:response postOperationsGetConnectivityServiceListCreated
*/
type PostOperationsGetConnectivityServiceListCreated struct {
}

// NewPostOperationsGetConnectivityServiceListCreated creates PostOperationsGetConnectivityServiceListCreated with default headers values
func NewPostOperationsGetConnectivityServiceListCreated() *PostOperationsGetConnectivityServiceListCreated {

	return &PostOperationsGetConnectivityServiceListCreated{}
}

// WriteResponse to the client
func (o *PostOperationsGetConnectivityServiceListCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsGetConnectivityServiceListBadRequestCode is the HTTP code returned for type PostOperationsGetConnectivityServiceListBadRequest
const PostOperationsGetConnectivityServiceListBadRequestCode int = 400

/*PostOperationsGetConnectivityServiceListBadRequest Internal error

swagger:response postOperationsGetConnectivityServiceListBadRequest
*/
type PostOperationsGetConnectivityServiceListBadRequest struct {
}

// NewPostOperationsGetConnectivityServiceListBadRequest creates PostOperationsGetConnectivityServiceListBadRequest with default headers values
func NewPostOperationsGetConnectivityServiceListBadRequest() *PostOperationsGetConnectivityServiceListBadRequest {

	return &PostOperationsGetConnectivityServiceListBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsGetConnectivityServiceListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
