// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi mef-common-types,tapi-connectivity-audit,tapi-topology,nrp-interface,tapi-common,mef-common,nrm-connectivity,tapi-path-computation,tapi-connectivity API
mef-common-types,tapi-connectivity-audit,tapi-topology,nrp-interface,tapi-common,mef-common,nrm-connectivity,tapi-path-computation,tapi-connectivity API generated from yang definitions


    Schemes:
      http
    Host: localhost:1234
    BasePath: /
    Version: 1.0

    Consumes:
    - application/yang-data+json

    Produces:
    - application/yang-data+json

swagger:meta
*/
package restapi
