// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi mef-common,tapi-topology,tapi-common,tapi-connectivity,mef-common-types,nrm-connectivity,nrp-interface API
MEF 60 (PRESTO NRP) swagger definition


    Schemes:
      http
    Host: localhost:1234
    BasePath: /restconf
    Version: 2018R2

    Consumes:
    - application/json
    - application/xml

    Produces:
    - application/json
    - application/xml

swagger:meta
*/
package restapi
