// Code generated by go-swagger; DO NOT EDIT.

package tapi_topology

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostOperationsGetNodeEdgePointDetailsHandlerFunc turns a function with the right signature into a post operations get node edge point details handler
type PostOperationsGetNodeEdgePointDetailsHandlerFunc func(PostOperationsGetNodeEdgePointDetailsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOperationsGetNodeEdgePointDetailsHandlerFunc) Handle(params PostOperationsGetNodeEdgePointDetailsParams) middleware.Responder {
	return fn(params)
}

// PostOperationsGetNodeEdgePointDetailsHandler interface for that can handle valid post operations get node edge point details params
type PostOperationsGetNodeEdgePointDetailsHandler interface {
	Handle(PostOperationsGetNodeEdgePointDetailsParams) middleware.Responder
}

// NewPostOperationsGetNodeEdgePointDetails creates a new http.Handler for the post operations get node edge point details operation
func NewPostOperationsGetNodeEdgePointDetails(ctx *middleware.Context, handler PostOperationsGetNodeEdgePointDetailsHandler) *PostOperationsGetNodeEdgePointDetails {
	return &PostOperationsGetNodeEdgePointDetails{Context: ctx, Handler: handler}
}

/*PostOperationsGetNodeEdgePointDetails swagger:route POST /operations/get-node-edge-point-details/ tapi-topology postOperationsGetNodeEdgePointDetails

PostOperationsGetNodeEdgePointDetails post operations get node edge point details API

*/
type PostOperationsGetNodeEdgePointDetails struct {
	Context *middleware.Context
	Handler PostOperationsGetNodeEdgePointDetailsHandler
}

func (o *PostOperationsGetNodeEdgePointDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostOperationsGetNodeEdgePointDetailsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
