// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MefCommonCosNameToPcpPac mef common cos name to pcp pac
// swagger:model mef.common.CosNameToPcpPac
type MefCommonCosNameToPcpPac struct {

	// This attribute denotes the ingress CoS name.
	IngressCosName string `json:"ingress-cos-name,omitempty"`

	// This attribute denotes the egress frame PCP value, mapped from ingress CoS Name and ingress frame color.
	PcpValue MefCommonTypesPcpOrDiscard `json:"pcp-value,omitempty"`
}

// Validate validates this mef common cos name to pcp pac
func (m *MefCommonCosNameToPcpPac) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePcpValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MefCommonCosNameToPcpPac) validatePcpValue(formats strfmt.Registry) error {

	if swag.IsZero(m.PcpValue) { // not required
		return nil
	}

	if err := m.PcpValue.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("pcp-value")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MefCommonCosNameToPcpPac) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MefCommonCosNameToPcpPac) UnmarshalBinary(b []byte) error {
	var res MefCommonCosNameToPcpPac
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
