// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// MefCommonTypesPcpOrDiscard mef common types pcp or discard
// swagger:model mef.common.types.PcpOrDiscard
type MefCommonTypesPcpOrDiscard string

const (

	// MefCommonTypesPcpOrDiscardDISCARD captures enum value "DISCARD"
	MefCommonTypesPcpOrDiscardDISCARD MefCommonTypesPcpOrDiscard = "DISCARD"

	// MefCommonTypesPcpOrDiscardNr0 captures enum value "0"
	MefCommonTypesPcpOrDiscardNr0 MefCommonTypesPcpOrDiscard = "0"

	// MefCommonTypesPcpOrDiscardNr1 captures enum value "1"
	MefCommonTypesPcpOrDiscardNr1 MefCommonTypesPcpOrDiscard = "1"

	// MefCommonTypesPcpOrDiscardNr2 captures enum value "2"
	MefCommonTypesPcpOrDiscardNr2 MefCommonTypesPcpOrDiscard = "2"

	// MefCommonTypesPcpOrDiscardNr3 captures enum value "3"
	MefCommonTypesPcpOrDiscardNr3 MefCommonTypesPcpOrDiscard = "3"

	// MefCommonTypesPcpOrDiscardNr4 captures enum value "4"
	MefCommonTypesPcpOrDiscardNr4 MefCommonTypesPcpOrDiscard = "4"

	// MefCommonTypesPcpOrDiscardNr5 captures enum value "5"
	MefCommonTypesPcpOrDiscardNr5 MefCommonTypesPcpOrDiscard = "5"

	// MefCommonTypesPcpOrDiscardNr6 captures enum value "6"
	MefCommonTypesPcpOrDiscardNr6 MefCommonTypesPcpOrDiscard = "6"

	// MefCommonTypesPcpOrDiscardNr7 captures enum value "7"
	MefCommonTypesPcpOrDiscardNr7 MefCommonTypesPcpOrDiscard = "7"
)

// for schema
var mefCommonTypesPcpOrDiscardEnum []interface{}

func init() {
	var res []MefCommonTypesPcpOrDiscard
	if err := json.Unmarshal([]byte(`["DISCARD","0","1","2","3","4","5","6","7"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		mefCommonTypesPcpOrDiscardEnum = append(mefCommonTypesPcpOrDiscardEnum, v)
	}
}

func (m MefCommonTypesPcpOrDiscard) validateMefCommonTypesPcpOrDiscardEnum(path, location string, value MefCommonTypesPcpOrDiscard) error {
	if err := validate.Enum(path, location, value, mefCommonTypesPcpOrDiscardEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this mef common types pcp or discard
func (m MefCommonTypesPcpOrDiscard) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateMefCommonTypesPcpOrDiscardEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
