// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MefCommonTypesVlanIDListing mef common types vlan Id listing
// swagger:model mef.common.types.VlanIdListing
type MefCommonTypesVlanIDListing struct {

	// Can be LIST, or ALL, or EXCEPT.
	Type MefCommonTypesVlanIDMappingType `json:"type,omitempty"`

	// This is a list of Vlan IDs.
	VlanIDList []*MefCommonTypesVlanID `json:"vlan-id-list"`
}

// Validate validates this mef common types vlan Id listing
func (m *MefCommonTypesVlanIDListing) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVlanIDList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MefCommonTypesVlanIDListing) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	if err := m.Type.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		}
		return err
	}

	return nil
}

func (m *MefCommonTypesVlanIDListing) validateVlanIDList(formats strfmt.Registry) error {

	if swag.IsZero(m.VlanIDList) { // not required
		return nil
	}

	for i := 0; i < len(m.VlanIDList); i++ {
		if swag.IsZero(m.VlanIDList[i]) { // not required
			continue
		}

		if m.VlanIDList[i] != nil {
			if err := m.VlanIDList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vlan-id-list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MefCommonTypesVlanIDListing) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MefCommonTypesVlanIDListing) UnmarshalBinary(b []byte) error {
	var res MefCommonTypesVlanIDListing
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
