// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MefCommonEnvelope mef common envelope
// swagger:model mef.common.Envelope
type MefCommonEnvelope struct {

	// This attribute denotes the coupling flag for index zero. FALSE for NO and TRUE for YES (overflow Green tokens can be used as Yellow tokens)
	CouplingFlagForIndexZero *bool `json:"coupling-flag-for-index-zero,omitempty"`

	// This attribute is a string that identifies the Envelope.
	EnvelopeID string `json:"envelope-id,omitempty"`
}

// Validate validates this mef common envelope
func (m *MefCommonEnvelope) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MefCommonEnvelope) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MefCommonEnvelope) UnmarshalBinary(b []byte) error {
	var res MefCommonEnvelope
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
