// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// MefCommonTypesDeiOrDiscard mef common types dei or discard
// swagger:model mef.common.types.DeiOrDiscard
type MefCommonTypesDeiOrDiscard string

const (

	// MefCommonTypesDeiOrDiscardDISCARD captures enum value "DISCARD"
	MefCommonTypesDeiOrDiscardDISCARD MefCommonTypesDeiOrDiscard = "DISCARD"

	// MefCommonTypesDeiOrDiscardNr0 captures enum value "0"
	MefCommonTypesDeiOrDiscardNr0 MefCommonTypesDeiOrDiscard = "0"

	// MefCommonTypesDeiOrDiscardNr1 captures enum value "1"
	MefCommonTypesDeiOrDiscardNr1 MefCommonTypesDeiOrDiscard = "1"
)

// for schema
var mefCommonTypesDeiOrDiscardEnum []interface{}

func init() {
	var res []MefCommonTypesDeiOrDiscard
	if err := json.Unmarshal([]byte(`["DISCARD","0","1"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		mefCommonTypesDeiOrDiscardEnum = append(mefCommonTypesDeiOrDiscardEnum, v)
	}
}

func (m MefCommonTypesDeiOrDiscard) validateMefCommonTypesDeiOrDiscardEnum(path, location string, value MefCommonTypesDeiOrDiscard) error {
	if err := validate.Enum(path, location, value, mefCommonTypesDeiOrDiscardEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this mef common types dei or discard
func (m MefCommonTypesDeiOrDiscard) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateMefCommonTypesDeiOrDiscardEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
