// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// MefCommonTypesTaggedL2cpProcessing mef common types tagged l2cp processing
// swagger:model mef.common.types.TaggedL2cpProcessing
type MefCommonTypesTaggedL2cpProcessing string

const (

	// MefCommonTypesTaggedL2cpProcessingNr8021COMPLIANT captures enum value "802.1_COMPLIANT"
	MefCommonTypesTaggedL2cpProcessingNr8021COMPLIANT MefCommonTypesTaggedL2cpProcessing = "802.1_COMPLIANT"

	// MefCommonTypesTaggedL2cpProcessingNr8021NONCOMPLIANT captures enum value "802.1_NON_COMPLIANT"
	MefCommonTypesTaggedL2cpProcessingNr8021NONCOMPLIANT MefCommonTypesTaggedL2cpProcessing = "802.1_NON_COMPLIANT"
)

// for schema
var mefCommonTypesTaggedL2cpProcessingEnum []interface{}

func init() {
	var res []MefCommonTypesTaggedL2cpProcessing
	if err := json.Unmarshal([]byte(`["802.1_COMPLIANT","802.1_NON_COMPLIANT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		mefCommonTypesTaggedL2cpProcessingEnum = append(mefCommonTypesTaggedL2cpProcessingEnum, v)
	}
}

func (m MefCommonTypesTaggedL2cpProcessing) validateMefCommonTypesTaggedL2cpProcessingEnum(path, location string, value MefCommonTypesTaggedL2cpProcessing) error {
	if err := validate.Enum(path, location, value, mefCommonTypesTaggedL2cpProcessingEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this mef common types tagged l2cp processing
func (m MefCommonTypesTaggedL2cpProcessing) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateMefCommonTypesTaggedL2cpProcessingEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
