// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MefCommonTypesSourceMacAddressLimit mef common types source mac address limit
// swagger:model mef.common.types.SourceMacAddressLimit
type MefCommonTypesSourceMacAddressLimit struct {

	// This attribute denotes the maximum acceptable source MAC addresses.
	Limit int64 `json:"limit,omitempty"`

	// This attribute denotes the time interval in milliseconds.
	TimeInterval int64 `json:"time-interval,omitempty"`
}

// Validate validates this mef common types source mac address limit
func (m *MefCommonTypesSourceMacAddressLimit) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MefCommonTypesSourceMacAddressLimit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MefCommonTypesSourceMacAddressLimit) UnmarshalBinary(b []byte) error {
	var res MefCommonTypesSourceMacAddressLimit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
