// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// MefCommonDeiColorIDPac mef common dei color Id pac
// swagger:model mef.common.DeiColorIdPac
type MefCommonDeiColorIDPac interface{}
