// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// MefCommonTypesL2cpProtocolType mef common types l2cp protocol type
// swagger:model mef.common.types.L2cpProtocolType
type MefCommonTypesL2cpProtocolType string

const (

	// MefCommonTypesL2cpProtocolTypeETHERTYPE captures enum value "ETHERTYPE"
	MefCommonTypesL2cpProtocolTypeETHERTYPE MefCommonTypesL2cpProtocolType = "ETHERTYPE"

	// MefCommonTypesL2cpProtocolTypeLLC captures enum value "LLC"
	MefCommonTypesL2cpProtocolTypeLLC MefCommonTypesL2cpProtocolType = "LLC"
)

// for schema
var mefCommonTypesL2cpProtocolTypeEnum []interface{}

func init() {
	var res []MefCommonTypesL2cpProtocolType
	if err := json.Unmarshal([]byte(`["ETHERTYPE","LLC"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		mefCommonTypesL2cpProtocolTypeEnum = append(mefCommonTypesL2cpProtocolTypeEnum, v)
	}
}

func (m MefCommonTypesL2cpProtocolType) validateMefCommonTypesL2cpProtocolTypeEnum(path, location string, value MefCommonTypesL2cpProtocolType) error {
	if err := validate.Enum(path, location, value, mefCommonTypesL2cpProtocolTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this mef common types l2cp protocol type
func (m MefCommonTypesL2cpProtocolType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateMefCommonTypesL2cpProtocolTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
