// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NrpInterfaceNrpCarrierEthInniNResource nrp interface nrp carrier eth inni n resource
// swagger:model nrp.interface.NrpCarrierEthInniNResource
type NrpInterfaceNrpCarrierEthInniNResource struct {

	// This attribute represents the L2CP Peering Service defined in MEF 45 section 8.2 when applied to the UNI/ENNI/INNI.
	L2cpPeeringList []*MefCommonTypesL2cpPeering `json:"l2cp-peering-list"`

	// This value indicates the maximum length of frames supported by this Interface.
	MaxFrameSize int64 `json:"max-frame-size,omitempty"`
}

// Validate validates this nrp interface nrp carrier eth inni n resource
func (m *NrpInterfaceNrpCarrierEthInniNResource) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateL2cpPeeringList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NrpInterfaceNrpCarrierEthInniNResource) validateL2cpPeeringList(formats strfmt.Registry) error {

	if swag.IsZero(m.L2cpPeeringList) { // not required
		return nil
	}

	for i := 0; i < len(m.L2cpPeeringList); i++ {
		if swag.IsZero(m.L2cpPeeringList[i]) { // not required
			continue
		}

		if m.L2cpPeeringList[i] != nil {
			if err := m.L2cpPeeringList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("l2cp-peering-list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *NrpInterfaceNrpCarrierEthInniNResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NrpInterfaceNrpCarrierEthInniNResource) UnmarshalBinary(b []byte) error {
	var res NrpInterfaceNrpCarrierEthInniNResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
