// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyValidationPac tapi topology validation pac
// swagger:model tapi.topology.ValidationPac
type TapiTopologyValidationPac struct {

	// Provides details of the specific validation mechanism(s) used to confirm the presence of an intended topologicalEntity.
	ValidationMechanism []*TapiTopologyValidationMechanism `json:"validation-mechanism"`
}

// Validate validates this tapi topology validation pac
func (m *TapiTopologyValidationPac) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValidationMechanism(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyValidationPac) validateValidationMechanism(formats strfmt.Registry) error {

	if swag.IsZero(m.ValidationMechanism) { // not required
		return nil
	}

	for i := 0; i < len(m.ValidationMechanism); i++ {
		if swag.IsZero(m.ValidationMechanism[i]) { // not required
			continue
		}

		if m.ValidationMechanism[i] != nil {
			if err := m.ValidationMechanism[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("validation-mechanism" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyValidationPac) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyValidationPac) UnmarshalBinary(b []byte) error {
	var res TapiTopologyValidationPac
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
