// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiPathComputationComputeP2PPathInput tapi path computation compute p2 p path input
// swagger:model tapi.path.computation.ComputeP2PPathInput
type TapiPathComputationComputeP2PPathInput struct {

	// input
	Input *TapiPathComputationComputeP2PPathInputInput `json:"input,omitempty"`
}

// Validate validates this tapi path computation compute p2 p path input
func (m *TapiPathComputationComputeP2PPathInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPathComputationComputeP2PPathInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPathComputationComputeP2PPathInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPathComputationComputeP2PPathInput) UnmarshalBinary(b []byte) error {
	var res TapiPathComputationComputeP2PPathInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiPathComputationComputeP2PPathInputInput tapi path computation compute p2 p path input input
// swagger:model TapiPathComputationComputeP2PPathInputInput
type TapiPathComputationComputeP2PPathInputInput struct {

	// none
	ObjectiveFunction *TapiPathComputationPathObjectiveFunction `json:"objective-function,omitempty"`

	// none
	RoutingConstraint *TapiPathComputationRoutingConstraint `json:"routing-constraint,omitempty"`

	// none
	Sep []*TapiPathComputationPathServiceEndPoint `json:"sep"`
}

// Validate validates this tapi path computation compute p2 p path input input
func (m *TapiPathComputationComputeP2PPathInputInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateObjectiveFunction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoutingConstraint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSep(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPathComputationComputeP2PPathInputInput) validateObjectiveFunction(formats strfmt.Registry) error {

	if swag.IsZero(m.ObjectiveFunction) { // not required
		return nil
	}

	if m.ObjectiveFunction != nil {
		if err := m.ObjectiveFunction.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input" + "." + "objective-function")
			}
			return err
		}
	}

	return nil
}

func (m *TapiPathComputationComputeP2PPathInputInput) validateRoutingConstraint(formats strfmt.Registry) error {

	if swag.IsZero(m.RoutingConstraint) { // not required
		return nil
	}

	if m.RoutingConstraint != nil {
		if err := m.RoutingConstraint.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input" + "." + "routing-constraint")
			}
			return err
		}
	}

	return nil
}

func (m *TapiPathComputationComputeP2PPathInputInput) validateSep(formats strfmt.Registry) error {

	if swag.IsZero(m.Sep) { // not required
		return nil
	}

	for i := 0; i < len(m.Sep); i++ {
		if swag.IsZero(m.Sep[i]) { // not required
			continue
		}

		if m.Sep[i] != nil {
			if err := m.Sep[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("input" + "." + "sep" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPathComputationComputeP2PPathInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPathComputationComputeP2PPathInputInput) UnmarshalBinary(b []byte) error {
	var res TapiPathComputationComputeP2PPathInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
