// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyGetLinkDetailsInput tapi topology get link details input
// swagger:model tapi.topology.GetLinkDetailsInput
type TapiTopologyGetLinkDetailsInput struct {

	// input
	Input *TapiTopologyGetLinkDetailsInputInput `json:"input,omitempty"`
}

// Validate validates this tapi topology get link details input
func (m *TapiTopologyGetLinkDetailsInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyGetLinkDetailsInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetLinkDetailsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetLinkDetailsInput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetLinkDetailsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiTopologyGetLinkDetailsInputInput tapi topology get link details input input
// swagger:model TapiTopologyGetLinkDetailsInputInput
type TapiTopologyGetLinkDetailsInputInput struct {

	// none
	LinkIDOrName string `json:"link-id-or-name,omitempty"`

	// none
	TopologyIDOrName string `json:"topology-id-or-name,omitempty"`
}

// Validate validates this tapi topology get link details input input
func (m *TapiTopologyGetLinkDetailsInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetLinkDetailsInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetLinkDetailsInputInput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetLinkDetailsInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
