// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyTransferTimingPac tapi topology transfer timing pac
// swagger:model tapi.topology.TransferTimingPac
type TapiTopologyTransferTimingPac struct {

	// The effect on the latency of a queuing process. This only has significant effect for packet based systems and has a complex characteristic.
	LatencyCharacteristic []*TapiTopologyLatencyCharacteristic `json:"latency-characteristic"`
}

// Validate validates this tapi topology transfer timing pac
func (m *TapiTopologyTransferTimingPac) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLatencyCharacteristic(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyTransferTimingPac) validateLatencyCharacteristic(formats strfmt.Registry) error {

	if swag.IsZero(m.LatencyCharacteristic) { // not required
		return nil
	}

	for i := 0; i < len(m.LatencyCharacteristic); i++ {
		if swag.IsZero(m.LatencyCharacteristic[i]) { // not required
			continue
		}

		if m.LatencyCharacteristic[i] != nil {
			if err := m.LatencyCharacteristic[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("latency-characteristic" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyTransferTimingPac) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyTransferTimingPac) UnmarshalBinary(b []byte) error {
	var res TapiTopologyTransferTimingPac
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
