// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiCommonPortRole tapi common port role
// swagger:model tapi.common.PortRole
type TapiCommonPortRole string

const (

	// TapiCommonPortRoleSYMMETRIC captures enum value "SYMMETRIC"
	TapiCommonPortRoleSYMMETRIC TapiCommonPortRole = "SYMMETRIC"

	// TapiCommonPortRoleROOT captures enum value "ROOT"
	TapiCommonPortRoleROOT TapiCommonPortRole = "ROOT"

	// TapiCommonPortRoleLEAF captures enum value "LEAF"
	TapiCommonPortRoleLEAF TapiCommonPortRole = "LEAF"

	// TapiCommonPortRoleTRUNK captures enum value "TRUNK"
	TapiCommonPortRoleTRUNK TapiCommonPortRole = "TRUNK"

	// TapiCommonPortRoleUNKNOWN captures enum value "UNKNOWN"
	TapiCommonPortRoleUNKNOWN TapiCommonPortRole = "UNKNOWN"
)

// for schema
var tapiCommonPortRoleEnum []interface{}

func init() {
	var res []TapiCommonPortRole
	if err := json.Unmarshal([]byte(`["SYMMETRIC","ROOT","LEAF","TRUNK","UNKNOWN"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiCommonPortRoleEnum = append(tapiCommonPortRoleEnum, v)
	}
}

func (m TapiCommonPortRole) validateTapiCommonPortRoleEnum(path, location string, value TapiCommonPortRole) error {
	if err := validate.Enum(path, location, value, tapiCommonPortRoleEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi common port role
func (m TapiCommonPortRole) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiCommonPortRoleEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
