// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityGetConnectionDetailsInput tapi connectivity get connection details input
// swagger:model tapi.connectivity.GetConnectionDetailsInput
type TapiConnectivityGetConnectionDetailsInput struct {

	// input
	Input *TapiConnectivityGetConnectionDetailsInputInput `json:"input,omitempty"`
}

// Validate validates this tapi connectivity get connection details input
func (m *TapiConnectivityGetConnectionDetailsInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityGetConnectionDetailsInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityGetConnectionDetailsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityGetConnectionDetailsInput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityGetConnectionDetailsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiConnectivityGetConnectionDetailsInputInput tapi connectivity get connection details input input
// swagger:model TapiConnectivityGetConnectionDetailsInputInput
type TapiConnectivityGetConnectionDetailsInputInput struct {

	// none
	ConnectionIDOrName string `json:"connection-id-or-name,omitempty"`

	// none
	ServiceIDOrName string `json:"service-id-or-name,omitempty"`
}

// Validate validates this tapi connectivity get connection details input input
func (m *TapiConnectivityGetConnectionDetailsInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityGetConnectionDetailsInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityGetConnectionDetailsInputInput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityGetConnectionDetailsInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
