// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiPathComputationOptimizeP2PPathOutput tapi path computation optimize p2 p path output
// swagger:model tapi.path.computation.OptimizeP2PPathOutput
type TapiPathComputationOptimizeP2PPathOutput struct {

	// output
	Output *TapiPathComputationOptimizeP2PPathOutputOutput `json:"output,omitempty"`
}

// Validate validates this tapi path computation optimize p2 p path output
func (m *TapiPathComputationOptimizeP2PPathOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOutput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPathComputationOptimizeP2PPathOutput) validateOutput(formats strfmt.Registry) error {

	if swag.IsZero(m.Output) { // not required
		return nil
	}

	if m.Output != nil {
		if err := m.Output.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPathComputationOptimizeP2PPathOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPathComputationOptimizeP2PPathOutput) UnmarshalBinary(b []byte) error {
	var res TapiPathComputationOptimizeP2PPathOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiPathComputationOptimizeP2PPathOutputOutput tapi path computation optimize p2 p path output output
// swagger:model TapiPathComputationOptimizeP2PPathOutputOutput
type TapiPathComputationOptimizeP2PPathOutputOutput struct {

	// none
	Service *TapiPathComputationPathComputationService `json:"service,omitempty"`
}

// Validate validates this tapi path computation optimize p2 p path output output
func (m *TapiPathComputationOptimizeP2PPathOutputOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPathComputationOptimizeP2PPathOutputOutput) validateService(formats strfmt.Registry) error {

	if swag.IsZero(m.Service) { // not required
		return nil
	}

	if m.Service != nil {
		if err := m.Service.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output" + "." + "service")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPathComputationOptimizeP2PPathOutputOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPathComputationOptimizeP2PPathOutputOutput) UnmarshalBinary(b []byte) error {
	var res TapiPathComputationOptimizeP2PPathOutputOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
