// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityDeleteConnectivityServiceInput tapi connectivity delete connectivity service input
// swagger:model tapi.connectivity.DeleteConnectivityServiceInput
type TapiConnectivityDeleteConnectivityServiceInput struct {

	// input
	Input *TapiConnectivityDeleteConnectivityServiceInputInput `json:"input,omitempty"`
}

// Validate validates this tapi connectivity delete connectivity service input
func (m *TapiConnectivityDeleteConnectivityServiceInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityDeleteConnectivityServiceInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityDeleteConnectivityServiceInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityDeleteConnectivityServiceInput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityDeleteConnectivityServiceInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiConnectivityDeleteConnectivityServiceInputInput tapi connectivity delete connectivity service input input
// swagger:model TapiConnectivityDeleteConnectivityServiceInputInput
type TapiConnectivityDeleteConnectivityServiceInputInput struct {

	// none
	ServiceIDOrName string `json:"service-id-or-name,omitempty"`
}

// Validate validates this tapi connectivity delete connectivity service input input
func (m *TapiConnectivityDeleteConnectivityServiceInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityDeleteConnectivityServiceInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityDeleteConnectivityServiceInputInput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityDeleteConnectivityServiceInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
