// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutput tapi connectivity audit get connectivity service audit details output
// swagger:model tapi.connectivity.audit.GetConnectivityServiceAuditDetailsOutput
type TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutput struct {

	// output
	Output *TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutputOutput `json:"output,omitempty"`
}

// Validate validates this tapi connectivity audit get connectivity service audit details output
func (m *TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOutput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutput) validateOutput(formats strfmt.Registry) error {

	if swag.IsZero(m.Output) { // not required
		return nil
	}

	if m.Output != nil {
		if err := m.Output.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutputOutput tapi connectivity audit get connectivity service audit details output output
// swagger:model TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutputOutput
type TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutputOutput struct {

	// none
	ServiceAudit *TapiConnectivityAuditGetconnectivityserviceauditdetailsOutputServiceAudit `json:"service-audit,omitempty"`
}

// Validate validates this tapi connectivity audit get connectivity service audit details output output
func (m *TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutputOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateServiceAudit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutputOutput) validateServiceAudit(formats strfmt.Registry) error {

	if swag.IsZero(m.ServiceAudit) { // not required
		return nil
	}

	if m.ServiceAudit != nil {
		if err := m.ServiceAudit.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output" + "." + "service-audit")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutputOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutputOutput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityAuditGetConnectivityServiceAuditDetailsOutputOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
