// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiPathComputationDeleteP2PPathInput tapi path computation delete p2 p path input
// swagger:model tapi.path.computation.DeleteP2PPathInput
type TapiPathComputationDeleteP2PPathInput struct {

	// input
	Input *TapiPathComputationDeleteP2PPathInputInput `json:"input,omitempty"`
}

// Validate validates this tapi path computation delete p2 p path input
func (m *TapiPathComputationDeleteP2PPathInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPathComputationDeleteP2PPathInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPathComputationDeleteP2PPathInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPathComputationDeleteP2PPathInput) UnmarshalBinary(b []byte) error {
	var res TapiPathComputationDeleteP2PPathInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiPathComputationDeleteP2PPathInputInput tapi path computation delete p2 p path input input
// swagger:model TapiPathComputationDeleteP2PPathInputInput
type TapiPathComputationDeleteP2PPathInputInput struct {

	// none
	PathIDOrName string `json:"path-id-or-name,omitempty"`
}

// Validate validates this tapi path computation delete p2 p path input input
func (m *TapiPathComputationDeleteP2PPathInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiPathComputationDeleteP2PPathInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPathComputationDeleteP2PPathInputInput) UnmarshalBinary(b []byte) error {
	var res TapiPathComputationDeleteP2PPathInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
