// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiTopologyValidationMechanism tapi topology validation mechanism
// swagger:model tapi.topology.ValidationMechanism
type TapiTopologyValidationMechanism struct {

	// State of validatiion
	LayerProtocolAdjacencyValidated string `json:"layer-protocol-adjacency-validated,omitempty"`

	// Name of mechanism used to validate adjacency
	ValidationMechanism string `json:"validation-mechanism,omitempty"`

	// Quality of validation (i.e. how likely is the stated validation to be invalid)
	ValidationRobustness string `json:"validation-robustness,omitempty"`
}

// Validate validates this tapi topology validation mechanism
func (m *TapiTopologyValidationMechanism) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyValidationMechanism) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyValidationMechanism) UnmarshalBinary(b []byte) error {
	var res TapiTopologyValidationMechanism
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
