// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiConnectivityReversionMode tapi connectivity reversion mode
// swagger:model tapi.connectivity.ReversionMode
type TapiConnectivityReversionMode string

const (

	// TapiConnectivityReversionModeREVERTIVE captures enum value "REVERTIVE"
	TapiConnectivityReversionModeREVERTIVE TapiConnectivityReversionMode = "REVERTIVE"

	// TapiConnectivityReversionModeNONREVERTIVE captures enum value "NON-REVERTIVE"
	TapiConnectivityReversionModeNONREVERTIVE TapiConnectivityReversionMode = "NON-REVERTIVE"
)

// for schema
var tapiConnectivityReversionModeEnum []interface{}

func init() {
	var res []TapiConnectivityReversionMode
	if err := json.Unmarshal([]byte(`["REVERTIVE","NON-REVERTIVE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiConnectivityReversionModeEnum = append(tapiConnectivityReversionModeEnum, v)
	}
}

func (m TapiConnectivityReversionMode) validateTapiConnectivityReversionModeEnum(path, location string, value TapiConnectivityReversionMode) error {
	if err := validate.Enum(path, location, value, tapiConnectivityReversionModeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi connectivity reversion mode
func (m TapiConnectivityReversionMode) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiConnectivityReversionModeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
