// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiPathComputationRoutingConstraint tapi path computation routing constraint
// swagger:model tapi.path.computation.RoutingConstraint
type TapiPathComputationRoutingConstraint struct {
	TapiCommonLocalClass

	// none
	AvoidTopology []string `json:"avoid-topology"`

	// The list of costs where each cost relates to some aspect of the TopologicalEntity.
	CostCharacteristic []*TapiTopologyCostCharacteristic `json:"cost-characteristic"`

	// none
	IncludeTopology []*TapiTopologyTopologyRef `json:"include-topology"`

	// The effect on the latency of a queuing process. This only has significant effect for packet based systems and has a complex characteristic.
	LatencyCharacteristic []*TapiTopologyLatencyCharacteristic `json:"latency-characteristic"`

	// none
	PathLayer []TapiCommonLayerProtocolName `json:"path-layer"`

	// none
	RequestedCapacity *TapiCommonCapacity `json:"requested-capacity,omitempty"`

	// An abstract value the meaning of which is mutually agreed – typically represents metrics such as - Class of service, priority, resiliency, availability
	ServiceLevel string `json:"service-level,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiPathComputationRoutingConstraint) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiCommonLocalClass
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiCommonLocalClass = aO0

	// AO1
	var dataAO1 struct {
		AvoidTopology []string `json:"avoid-topology"`

		CostCharacteristic []*TapiTopologyCostCharacteristic `json:"cost-characteristic"`

		IncludeTopology []*TapiTopologyTopologyRef `json:"include-topology"`

		LatencyCharacteristic []*TapiTopologyLatencyCharacteristic `json:"latency-characteristic"`

		PathLayer []TapiCommonLayerProtocolName `json:"path-layer"`

		RequestedCapacity *TapiCommonCapacity `json:"requested-capacity,omitempty"`

		ServiceLevel string `json:"service-level,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.AvoidTopology = dataAO1.AvoidTopology

	m.CostCharacteristic = dataAO1.CostCharacteristic

	m.IncludeTopology = dataAO1.IncludeTopology

	m.LatencyCharacteristic = dataAO1.LatencyCharacteristic

	m.PathLayer = dataAO1.PathLayer

	m.RequestedCapacity = dataAO1.RequestedCapacity

	m.ServiceLevel = dataAO1.ServiceLevel

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiPathComputationRoutingConstraint) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.TapiCommonLocalClass)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		AvoidTopology []string `json:"avoid-topology"`

		CostCharacteristic []*TapiTopologyCostCharacteristic `json:"cost-characteristic"`

		IncludeTopology []*TapiTopologyTopologyRef `json:"include-topology"`

		LatencyCharacteristic []*TapiTopologyLatencyCharacteristic `json:"latency-characteristic"`

		PathLayer []TapiCommonLayerProtocolName `json:"path-layer"`

		RequestedCapacity *TapiCommonCapacity `json:"requested-capacity,omitempty"`

		ServiceLevel string `json:"service-level,omitempty"`
	}

	dataAO1.AvoidTopology = m.AvoidTopology

	dataAO1.CostCharacteristic = m.CostCharacteristic

	dataAO1.IncludeTopology = m.IncludeTopology

	dataAO1.LatencyCharacteristic = m.LatencyCharacteristic

	dataAO1.PathLayer = m.PathLayer

	dataAO1.RequestedCapacity = m.RequestedCapacity

	dataAO1.ServiceLevel = m.ServiceLevel

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi path computation routing constraint
func (m *TapiPathComputationRoutingConstraint) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiCommonLocalClass
	if err := m.TapiCommonLocalClass.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCostCharacteristic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIncludeTopology(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLatencyCharacteristic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePathLayer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequestedCapacity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPathComputationRoutingConstraint) validateCostCharacteristic(formats strfmt.Registry) error {

	if swag.IsZero(m.CostCharacteristic) { // not required
		return nil
	}

	for i := 0; i < len(m.CostCharacteristic); i++ {
		if swag.IsZero(m.CostCharacteristic[i]) { // not required
			continue
		}

		if m.CostCharacteristic[i] != nil {
			if err := m.CostCharacteristic[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cost-characteristic" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiPathComputationRoutingConstraint) validateIncludeTopology(formats strfmt.Registry) error {

	if swag.IsZero(m.IncludeTopology) { // not required
		return nil
	}

	for i := 0; i < len(m.IncludeTopology); i++ {
		if swag.IsZero(m.IncludeTopology[i]) { // not required
			continue
		}

		if m.IncludeTopology[i] != nil {
			if err := m.IncludeTopology[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("include-topology" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiPathComputationRoutingConstraint) validateLatencyCharacteristic(formats strfmt.Registry) error {

	if swag.IsZero(m.LatencyCharacteristic) { // not required
		return nil
	}

	for i := 0; i < len(m.LatencyCharacteristic); i++ {
		if swag.IsZero(m.LatencyCharacteristic[i]) { // not required
			continue
		}

		if m.LatencyCharacteristic[i] != nil {
			if err := m.LatencyCharacteristic[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("latency-characteristic" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiPathComputationRoutingConstraint) validatePathLayer(formats strfmt.Registry) error {

	if swag.IsZero(m.PathLayer) { // not required
		return nil
	}

	for i := 0; i < len(m.PathLayer); i++ {

		if err := m.PathLayer[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("path-layer" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *TapiPathComputationRoutingConstraint) validateRequestedCapacity(formats strfmt.Registry) error {

	if swag.IsZero(m.RequestedCapacity) { // not required
		return nil
	}

	if m.RequestedCapacity != nil {
		if err := m.RequestedCapacity.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("requested-capacity")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPathComputationRoutingConstraint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPathComputationRoutingConstraint) UnmarshalBinary(b []byte) error {
	var res TapiPathComputationRoutingConstraint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
