// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyGetTopologyDetailsOutput tapi topology get topology details output
// swagger:model tapi.topology.GetTopologyDetailsOutput
type TapiTopologyGetTopologyDetailsOutput struct {

	// output
	Output *TapiTopologyGetTopologyDetailsOutputOutput `json:"output,omitempty"`
}

// Validate validates this tapi topology get topology details output
func (m *TapiTopologyGetTopologyDetailsOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOutput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyGetTopologyDetailsOutput) validateOutput(formats strfmt.Registry) error {

	if swag.IsZero(m.Output) { // not required
		return nil
	}

	if m.Output != nil {
		if err := m.Output.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetTopologyDetailsOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetTopologyDetailsOutput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetTopologyDetailsOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiTopologyGetTopologyDetailsOutputOutput tapi topology get topology details output output
// swagger:model TapiTopologyGetTopologyDetailsOutputOutput
type TapiTopologyGetTopologyDetailsOutputOutput struct {

	// none
	Topology *TapiTopologyTopology `json:"topology,omitempty"`
}

// Validate validates this tapi topology get topology details output output
func (m *TapiTopologyGetTopologyDetailsOutputOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTopology(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyGetTopologyDetailsOutputOutput) validateTopology(formats strfmt.Registry) error {

	if swag.IsZero(m.Topology) { // not required
		return nil
	}

	if m.Topology != nil {
		if err := m.Topology.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output" + "." + "topology")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetTopologyDetailsOutputOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetTopologyDetailsOutputOutput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetTopologyDetailsOutputOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
