// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyResilienceType tapi topology resilience type
// swagger:model tapi.topology.ResilienceType
type TapiTopologyResilienceType struct {

	// none
	ProtectionType TapiTopologyProtectionType `json:"protection-type,omitempty"`

	// none
	RestorationPolicy TapiTopologyRestorationPolicy `json:"restoration-policy,omitempty"`
}

// Validate validates this tapi topology resilience type
func (m *TapiTopologyResilienceType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProtectionType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRestorationPolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyResilienceType) validateProtectionType(formats strfmt.Registry) error {

	if swag.IsZero(m.ProtectionType) { // not required
		return nil
	}

	if err := m.ProtectionType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("protection-type")
		}
		return err
	}

	return nil
}

func (m *TapiTopologyResilienceType) validateRestorationPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.RestorationPolicy) { // not required
		return nil
	}

	if err := m.RestorationPolicy.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("restoration-policy")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyResilienceType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyResilienceType) UnmarshalBinary(b []byte) error {
	var res TapiTopologyResilienceType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
