// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiTopologyProtectionType tapi topology protection type
// swagger:model tapi.topology.ProtectionType
type TapiTopologyProtectionType string

const (

	// TapiTopologyProtectionTypeNOPROTECTON captures enum value "NO_PROTECTON"
	TapiTopologyProtectionTypeNOPROTECTON TapiTopologyProtectionType = "NO_PROTECTON"

	// TapiTopologyProtectionTypeONEPLUSONEPROTECTION captures enum value "ONE_PLUS_ONE_PROTECTION"
	TapiTopologyProtectionTypeONEPLUSONEPROTECTION TapiTopologyProtectionType = "ONE_PLUS_ONE_PROTECTION"

	// TapiTopologyProtectionTypeONEPLUSONEPROTECTIONWITHDYNAMICRESTORATION captures enum value "ONE_PLUS_ONE_PROTECTION_WITH_DYNAMIC_RESTORATION"
	TapiTopologyProtectionTypeONEPLUSONEPROTECTIONWITHDYNAMICRESTORATION TapiTopologyProtectionType = "ONE_PLUS_ONE_PROTECTION_WITH_DYNAMIC_RESTORATION"

	// TapiTopologyProtectionTypePERMANENTONEPLUSONEPROTECTION captures enum value "PERMANENT_ONE_PLUS_ONE_PROTECTION"
	TapiTopologyProtectionTypePERMANENTONEPLUSONEPROTECTION TapiTopologyProtectionType = "PERMANENT_ONE_PLUS_ONE_PROTECTION"

	// TapiTopologyProtectionTypeONEFORONEPROTECTION captures enum value "ONE_FOR_ONE_PROTECTION"
	TapiTopologyProtectionTypeONEFORONEPROTECTION TapiTopologyProtectionType = "ONE_FOR_ONE_PROTECTION"

	// TapiTopologyProtectionTypeDYNAMICRESTORATION captures enum value "DYNAMIC_RESTORATION"
	TapiTopologyProtectionTypeDYNAMICRESTORATION TapiTopologyProtectionType = "DYNAMIC_RESTORATION"

	// TapiTopologyProtectionTypePRECOMPUTEDRESTORATION captures enum value "PRE_COMPUTED_RESTORATION"
	TapiTopologyProtectionTypePRECOMPUTEDRESTORATION TapiTopologyProtectionType = "PRE_COMPUTED_RESTORATION"
)

// for schema
var tapiTopologyProtectionTypeEnum []interface{}

func init() {
	var res []TapiTopologyProtectionType
	if err := json.Unmarshal([]byte(`["NO_PROTECTON","ONE_PLUS_ONE_PROTECTION","ONE_PLUS_ONE_PROTECTION_WITH_DYNAMIC_RESTORATION","PERMANENT_ONE_PLUS_ONE_PROTECTION","ONE_FOR_ONE_PROTECTION","DYNAMIC_RESTORATION","PRE_COMPUTED_RESTORATION"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiTopologyProtectionTypeEnum = append(tapiTopologyProtectionTypeEnum, v)
	}
}

func (m TapiTopologyProtectionType) validateTapiTopologyProtectionTypeEnum(path, location string, value TapiTopologyProtectionType) error {
	if err := validate.Enum(path, location, value, tapiTopologyProtectionTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi topology protection type
func (m TapiTopologyProtectionType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiTopologyProtectionTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
