// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiCommonOperationalStatePac tapi common operational state pac
// swagger:model tapi.common.OperationalStatePac
type TapiCommonOperationalStatePac struct {

	// none
	LifecycleState TapiCommonLifecycleState `json:"lifecycle-state,omitempty"`

	// none
	OperationalState TapiCommonOperationalState `json:"operational-state,omitempty"`
}

// Validate validates this tapi common operational state pac
func (m *TapiCommonOperationalStatePac) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLifecycleState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOperationalState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiCommonOperationalStatePac) validateLifecycleState(formats strfmt.Registry) error {

	if swag.IsZero(m.LifecycleState) { // not required
		return nil
	}

	if err := m.LifecycleState.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("lifecycle-state")
		}
		return err
	}

	return nil
}

func (m *TapiCommonOperationalStatePac) validateOperationalState(formats strfmt.Registry) error {

	if swag.IsZero(m.OperationalState) { // not required
		return nil
	}

	if err := m.OperationalState.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("operational-state")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiCommonOperationalStatePac) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiCommonOperationalStatePac) UnmarshalBinary(b []byte) error {
	var res TapiCommonOperationalStatePac
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
