// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyGetLinkDetailsOutput tapi topology get link details output
// swagger:model tapi.topology.GetLinkDetailsOutput
type TapiTopologyGetLinkDetailsOutput struct {

	// output
	Output *TapiTopologyGetLinkDetailsOutputOutput `json:"output,omitempty"`
}

// Validate validates this tapi topology get link details output
func (m *TapiTopologyGetLinkDetailsOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOutput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyGetLinkDetailsOutput) validateOutput(formats strfmt.Registry) error {

	if swag.IsZero(m.Output) { // not required
		return nil
	}

	if m.Output != nil {
		if err := m.Output.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetLinkDetailsOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetLinkDetailsOutput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetLinkDetailsOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiTopologyGetLinkDetailsOutputOutput tapi topology get link details output output
// swagger:model TapiTopologyGetLinkDetailsOutputOutput
type TapiTopologyGetLinkDetailsOutputOutput struct {

	// none
	Link *TapiTopologyLink `json:"link,omitempty"`
}

// Validate validates this tapi topology get link details output output
func (m *TapiTopologyGetLinkDetailsOutputOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyGetLinkDetailsOutputOutput) validateLink(formats strfmt.Registry) error {

	if swag.IsZero(m.Link) { // not required
		return nil
	}

	if m.Link != nil {
		if err := m.Link.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output" + "." + "link")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetLinkDetailsOutputOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetLinkDetailsOutputOutput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetLinkDetailsOutputOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
