// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiCommonTerminationState tapi common termination state
// swagger:model tapi.common.TerminationState
type TapiCommonTerminationState string

const (

	// TapiCommonTerminationStateLPCANNEVERTERMINATE captures enum value "LP_CAN_NEVER_TERMINATE"
	TapiCommonTerminationStateLPCANNEVERTERMINATE TapiCommonTerminationState = "LP_CAN_NEVER_TERMINATE"

	// TapiCommonTerminationStateLTNOTTERMINATED captures enum value "LT_NOT_TERMINATED"
	TapiCommonTerminationStateLTNOTTERMINATED TapiCommonTerminationState = "LT_NOT_TERMINATED"

	// TapiCommonTerminationStateTERMINATEDSERVERTOCLIENTFLOW captures enum value "TERMINATED_SERVER_TO_CLIENT_FLOW"
	TapiCommonTerminationStateTERMINATEDSERVERTOCLIENTFLOW TapiCommonTerminationState = "TERMINATED_SERVER_TO_CLIENT_FLOW"

	// TapiCommonTerminationStateTERMINATEDCLIENTTOSERVERFLOW captures enum value "TERMINATED_CLIENT_TO_SERVER_FLOW"
	TapiCommonTerminationStateTERMINATEDCLIENTTOSERVERFLOW TapiCommonTerminationState = "TERMINATED_CLIENT_TO_SERVER_FLOW"

	// TapiCommonTerminationStateTERMINATEDBIDIRECTIONAL captures enum value "TERMINATED_BIDIRECTIONAL"
	TapiCommonTerminationStateTERMINATEDBIDIRECTIONAL TapiCommonTerminationState = "TERMINATED_BIDIRECTIONAL"

	// TapiCommonTerminationStateLTPERMENANTLYTERMINATED captures enum value "LT_PERMENANTLY_TERMINATED"
	TapiCommonTerminationStateLTPERMENANTLYTERMINATED TapiCommonTerminationState = "LT_PERMENANTLY_TERMINATED"

	// TapiCommonTerminationStateTERMINATIONSTATEUNKNOWN captures enum value "TERMINATION_STATE_UNKNOWN"
	TapiCommonTerminationStateTERMINATIONSTATEUNKNOWN TapiCommonTerminationState = "TERMINATION_STATE_UNKNOWN"
)

// for schema
var tapiCommonTerminationStateEnum []interface{}

func init() {
	var res []TapiCommonTerminationState
	if err := json.Unmarshal([]byte(`["LP_CAN_NEVER_TERMINATE","LT_NOT_TERMINATED","TERMINATED_SERVER_TO_CLIENT_FLOW","TERMINATED_CLIENT_TO_SERVER_FLOW","TERMINATED_BIDIRECTIONAL","LT_PERMENANTLY_TERMINATED","TERMINATION_STATE_UNKNOWN"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiCommonTerminationStateEnum = append(tapiCommonTerminationStateEnum, v)
	}
}

func (m TapiCommonTerminationState) validateTapiCommonTerminationStateEnum(path, location string, value TapiCommonTerminationState) error {
	if err := validate.Enum(path, location, value, tapiCommonTerminationStateEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi common termination state
func (m TapiCommonTerminationState) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiCommonTerminationStateEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
