// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyGetTopologyDetailsInput tapi topology get topology details input
// swagger:model tapi.topology.GetTopologyDetailsInput
type TapiTopologyGetTopologyDetailsInput struct {

	// input
	Input *TapiTopologyGetTopologyDetailsInputInput `json:"input,omitempty"`
}

// Validate validates this tapi topology get topology details input
func (m *TapiTopologyGetTopologyDetailsInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyGetTopologyDetailsInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetTopologyDetailsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetTopologyDetailsInput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetTopologyDetailsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiTopologyGetTopologyDetailsInputInput tapi topology get topology details input input
// swagger:model TapiTopologyGetTopologyDetailsInputInput
type TapiTopologyGetTopologyDetailsInputInput struct {

	// none
	TopologyIDOrName string `json:"topology-id-or-name,omitempty"`
}

// Validate validates this tapi topology get topology details input input
func (m *TapiTopologyGetTopologyDetailsInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetTopologyDetailsInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetTopologyDetailsInputInput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetTopologyDetailsInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
