// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyRiskParameterPac tapi topology risk parameter pac
// swagger:model tapi.topology.RiskParameterPac
type TapiTopologyRiskParameterPac struct {

	// A list of risk characteristics for consideration in an analysis of shared risk. Each element of the list represents a specific risk consideration.
	RiskCharacteristic []*TapiTopologyRiskCharacteristic `json:"risk-characteristic"`
}

// Validate validates this tapi topology risk parameter pac
func (m *TapiTopologyRiskParameterPac) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRiskCharacteristic(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyRiskParameterPac) validateRiskCharacteristic(formats strfmt.Registry) error {

	if swag.IsZero(m.RiskCharacteristic) { // not required
		return nil
	}

	for i := 0; i < len(m.RiskCharacteristic); i++ {
		if swag.IsZero(m.RiskCharacteristic[i]) { // not required
			continue
		}

		if m.RiskCharacteristic[i] != nil {
			if err := m.RiskCharacteristic[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("risk-characteristic" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyRiskParameterPac) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyRiskParameterPac) UnmarshalBinary(b []byte) error {
	var res TapiTopologyRiskParameterPac
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
