// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiCommonNameAndValue tapi common name and value
// swagger:model tapi.common.NameAndValue
type TapiCommonNameAndValue struct {

	// The value
	Value string `json:"value,omitempty"`

	// The name of the value. The value need not have a name.
	ValueName string `json:"value-name,omitempty"`
}

// Validate validates this tapi common name and value
func (m *TapiCommonNameAndValue) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiCommonNameAndValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiCommonNameAndValue) UnmarshalBinary(b []byte) error {
	var res TapiCommonNameAndValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
