// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityRouteComputePolicy tapi connectivity route compute policy
// swagger:model tapi.connectivity.RouteComputePolicy
type TapiConnectivityRouteComputePolicy struct {

	// none
	DiversityPolicy TapiConnectivityDiversityPolicy `json:"diversity-policy,omitempty"`

	// none
	RouteObjectiveFunction TapiConnectivityRouteObjectiveFunction `json:"route-objective-function,omitempty"`
}

// Validate validates this tapi connectivity route compute policy
func (m *TapiConnectivityRouteComputePolicy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDiversityPolicy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRouteObjectiveFunction(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityRouteComputePolicy) validateDiversityPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.DiversityPolicy) { // not required
		return nil
	}

	if err := m.DiversityPolicy.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("diversity-policy")
		}
		return err
	}

	return nil
}

func (m *TapiConnectivityRouteComputePolicy) validateRouteObjectiveFunction(formats strfmt.Registry) error {

	if swag.IsZero(m.RouteObjectiveFunction) { // not required
		return nil
	}

	if err := m.RouteObjectiveFunction.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("route-objective-function")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityRouteComputePolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityRouteComputePolicy) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityRouteComputePolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
