// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiCommonServiceInterfacePointRef tapi common service interface point ref
// swagger:model tapi.common.ServiceInterfacePointRef
type TapiCommonServiceInterfacePointRef struct {

	// service interface point id
	ServiceInterfacePointID string `json:"service-interface-point-id,omitempty"`
}

// Validate validates this tapi common service interface point ref
func (m *TapiCommonServiceInterfacePointRef) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiCommonServiceInterfacePointRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiCommonServiceInterfacePointRef) UnmarshalBinary(b []byte) error {
	var res TapiCommonServiceInterfacePointRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
