// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyGetNodeDetailsInput tapi topology get node details input
// swagger:model tapi.topology.GetNodeDetailsInput
type TapiTopologyGetNodeDetailsInput struct {

	// input
	Input *TapiTopologyGetNodeDetailsInputInput `json:"input,omitempty"`
}

// Validate validates this tapi topology get node details input
func (m *TapiTopologyGetNodeDetailsInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyGetNodeDetailsInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetNodeDetailsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetNodeDetailsInput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetNodeDetailsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiTopologyGetNodeDetailsInputInput tapi topology get node details input input
// swagger:model TapiTopologyGetNodeDetailsInputInput
type TapiTopologyGetNodeDetailsInputInput struct {

	// none
	NodeIDOrName string `json:"node-id-or-name,omitempty"`

	// none
	TopologyIDOrName string `json:"topology-id-or-name,omitempty"`
}

// Validate validates this tapi topology get node details input input
func (m *TapiTopologyGetNodeDetailsInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetNodeDetailsInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetNodeDetailsInputInput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetNodeDetailsInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
