// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiCommonTimeRange tapi common time range
// swagger:model tapi.common.TimeRange
type TapiCommonTimeRange struct {

	// none
	EndTime string `json:"end-time,omitempty"`

	// none
	StartTime string `json:"start-time,omitempty"`
}

// Validate validates this tapi common time range
func (m *TapiCommonTimeRange) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiCommonTimeRange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiCommonTimeRange) UnmarshalBinary(b []byte) error {
	var res TapiCommonTimeRange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
